#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for dir in `find /home/user -regextype posix-extended -regex ".*/Backup-[0-9]{4}-[0-9]{2}-[0-9]{2}"`
do
	dateOfDirStr=`echo "$dir" | awk -F '-' '{print $2"-"$3"-"$4}'`
	dateOfDir=`date -d "dateOfDirStr" '+%s'`
	curDate=`date '+%s'`
	diffInDays=$((($curDate-$dateOfDir)/85400))
	if [[ "$diffInDays" -lt "7" ]]
	then
		fullNameYoungDir="$dir"
	fi
done

if [[ -z "$fullNameYoungDir" ]]
then
	# In that case creating new directory
	echo "Creating new directory"
	now=`date +'%Y-%m-%d'`
	name="/home/user/Backup-"$now
	cp -R "/home/user/source" "$name"
	back_rep="/home/user/backup-report"
	echo "#######################################" >> "$back_rep"
	echo "Name: ""$name" >> "$back_rep"
	echo "Date: "$now >> "$back_rep"
	echo "Content: " >> "$back_rep"
	
	cd "$name"
	find * -type f >> "$back_rep"
else
	# No need to mk new dir
	echo "No need to make new directory"
	echo "######################################" >> "$back_rep"
	echo "Name: ""$fullNameYoungDir" >> "$back_rep"
	echo "Date: "`date +'%Y-%m-%d'` >> "$back_rep"
	echo "Changes: " >> "$back_rep"
	cd /home/user/source

	for file in `find * -type f `
	do
		if [[ -f "$fullNameYoungDir""/""$file" ]]
			then
				if ((`stat -c%s "$fullNameYoungDir""/""$file"`==`stat -c%s "file"`))
					then
						echo "!!!! Same !!!!"
					else
						echo "Different"
						newname="$fullNameYoungDir""/""$file"'-'`date +'%Y-%m-%d'`
						mv "$fullNameYoungDir""/""$file" "$newname"
						path = `echo "$file" | awk 'BEGIN{FS="/"; OFS="/"} {NF-- ; print}'`
						cp "$file" "$fullNameYoungDir""/""$file"
						echo "Changed: ""$file" "$newname" >> /home/user/.tmp
					fi
			else
				path=`echo "$file" | awk 'BEGIN{FS"/"; OFS="/"} {NF--; print}'`
				cp "$file" "$fullNameYoungDir""/""$file"
				echo "Added: ""$file" >> "$back_rep"
			fi
	done
fi

if [[ -f /home/user/.tmp ]]
then
	cat /home/user/.tmp >> /home/user/backup-report
	rm /home/user/.tmp
fi
