#!/bin/bash

file_name="$1"
path_to_trash=$HOME'/.trash'

if [ -d $path_to_trash ]
then 
	echo 'catalog /~/.trash exists!'
else
	echo 'catalog /~/.trash does not exist!'
	echo 'creating hidden catalog trash...'
	mkdir $path_to_trash
	echo 'hidden catalog trash successfully created!'
fi

unique_name=`date +'%d.%m.%y.%T'`
path_in_trash=$path_to_trash'/'$unique_name
echo 'Moving file to '$path_in_trash

if [[ -f "$file_name" ]]
then
	ln "$file_name" $path_in_trash && {
		rm "$file_name"
		echo $PWD/"$file_name""|"$unique_name >> ~/.trash.log
}
else
	echo "Such file does not exist"
fi
